services:
  socket-server:
    container_name: rnd-socket-server
    build:
      context: .
      dockerfile: Dockerfile.server.local
    ports:
      - 3000:3000
    restart: always
    networks:
      - socket-test

  socket-client-1:
    container_name: rnd-socket-client-1
    build:
      context: .
      dockerfile: Dockerfile.client.local
    restart: always
    networks:
      - socket-test

networks:
  socket-test:
    driver: bridge
