services:
  socket-server:
    container_name: rnd-socket-server
    build:
      context: ./server
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    restart: always
    networks:
      - socket-test

  socket-client-1:
    container_name: rnd-socket-client-1
    build:
      context: ./js-client
      dockerfile: Dockerfile.local
    environment:
      - HOST=socket-server
    restart: always
    networks:
      - socket-test
  
  socket-client-2:
    container_name: rnd-socket-client-2
    build:
      context: ./client
      dockerfile: Dockerfile.client.local
    restart: always
    networks:
      - socket-test
  
  socket-client-3:
    container_name: rnd-socket-client-3
    build:
      context: ./client
      dockerfile: Dockerfile.client.local
    restart: always
    networks:
      - socket-test
  
  socket-client-4:
    container_name: rnd-socket-client-4
    build:
      context: ./client
      dockerfile: Dockerfile.client.local
    restart: always
    networks:
      - socket-test

networks:
  socket-test:
    driver: bridge
