services:
  socket-server:
    container_name: rnd-socket-server
    build:
      context: ./server
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    restart: always
    networks:
      - socket-test

  socket-client-1:
    container_name: rnd-socket-client-1
    build:
      context: ./js-client
      dockerfile: Dockerfile.local
    environment:
      - HOST=socket-server
    restart: always
    networks:
      - socket-test
  
  python-socket-client-1:
    container_name: python-socket-client-1
    build:
      context: ./python-client
      dockerfile: Dockerfile.local
    environment:
      - HOST=socket-server
    restart: always
    networks:
      - socket-test

networks:
  socket-test:
    driver: bridge
